### ISSUE TITLE
Did you put your code somewhere else...?

### ISSUE THREAD

**Issue by nelsonic** [SimonLab/hapi-auth-google-example#1]
![git fire](https://camo.githubusercontent.com/3ab8156bb4d519275f021d79a92a04674dc56594/68747470733a2f2f692e696d6775722e636f6d2f33504f747665432e6a7067)

I saw you had done a bit of work on this but it does not appear to be online...
let me know if you are still working on this or if I can add an example. thanks. :+1:

**Comment by SimonLab** [comment]
@nelsonic I haven't push my code yet (there is only smoke) and I'm just at the beginning of the example. Please add your example if you think you have more complete example!

**Comment by SimonLab** [comment]
The code is online now!

**Comment by nelsonic** [comment]
:+1:
